### ISSUE TITLE
Score Saving System.

### ISSUE THREAD

**Issue by TenmaUchiyama** [TenmaUchiyama/BombPassing#25]
# Outline 
Save the final score and save it so that the application can refer to the past score even if it's closed. 

# Duration

# Tasks
- [ ] Display the counts
- [ ] Save the new score in a file 
- [ ] refer to the past score from the file 
- [ ] Compare and display the score
