### ISSUE TITLE
Wind System

### ISSUE THREAD

**Issue by TenmaUchiyama** [TenmaUchiyama/BombPassing#30]
# Outline 
Add the wind system. 

# Duration

# Tasks
- [ ] Add simpel wind features that push the bomb
- [ ] Wind starts after 10 pass, otherwise not.
- [ ] Wind occurs random direction. 
- [ ] Wind occurs randomly. Sometimes it does sometime not.
