### ISSUE TITLE
Change the Scaled Data

### ISSUE THREAD

**Issue by TenmaUchiyama** [TenmaUchiyama/BombPassing#45]
# Outline 
Set the number to the best number. 
# Duration

# Tasks
- [x] Set Gravity Scale : 0.3
- [x] Set Timer Speed :  15
- [x] Set Time Penalize Size : 1.5  
- [x] Set Time Addition SIze :  300
- [x] Set Wind Force Scale Small : 
- [x] Set Wind Force Scale  Medium:
- [x] Set Wind Force Scale Large:
- [ ]
