### ISSUE TITLE
Game Over Screen 

### ISSUE THREAD

**Issue by TenmaUchiyama** [TenmaUchiyama/BombPassing#8]
# Outline 
Modify the style of the Game Over Screen buttons to follow the Desert Theme. 

# Duration

# Tasks
- [ ] 1 Highscore
- [ ] Dark / Black background
- [ ] Retry / Main menu buttons
- [ ] Modify style to Desert theme
