### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by TenmaUchiyama** [TenmaUchiyama/BombPassing#9]
# Outline 
Design and implement the main menu.

Add the new Sprite of Button and Backgrond Img

# Tasks
- [ ] Place camera in scene with focus on table and bomb
- [ ] Remove "Return button" or relabel "Exit" and make it close the game
- [ ] Modify style to fit Desert theme
